import streamlit as st
import os
import io
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from data import get_student_data, get_student_skills, get_student_projects
import json

CAREER_KB_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "career_kb.json")

def generate_student_pdf(active_sid):
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    
    student = get_student_data(active_sid)
    skills_data = get_student_skills(active_sid)
    projects_data = get_student_projects(active_sid)
    
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 50, "SMARTCAMPUS AI")
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 70, "Student Academic & Career Analysis Report")
    
    c.drawString(50, height - 100, f"Student ID: {student.get('student_id')}")
    c.drawString(50, height - 115, f"Name: {student.get('full_name')}")
    
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 145, "ACADEMIC SUMMARY")
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 165, f"Attendance: {student.get('attendance')}%")
    c.drawString(50, height - 180, f"Study Hours: {student.get('study_hours')} hrs/day")
    c.drawString(50, height - 195, f"Performance Level: {student.get('level')}")
    c.drawString(50, height - 210, f"Risk Level: {student.get('risk')}")
    
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 240, "PROJECT ANALYSIS")
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 260, f"Total Projects: {len(projects_data)}")
    
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 290, "CAREER & SKILL GAP ANALYSIS")
    c.setFont("Helvetica", 12)
    
    student_skills = [s["name"] for s in skills_data]
    
    with open(CAREER_KB_PATH, "r") as f:
        career_kb = json.load(f)
        
    career_matches = []
    for role, role_data in career_kb.items():
        core = set([s.lower() for s in role_data["core_skills"]])
        student_sk_lower = set([s.lower() for s in student_skills])
        match_count = len(core.intersection(student_sk_lower))
        career_matches.append((role, match_count))
        
    career_matches.sort(key=lambda x: x[1], reverse=True)
    top_career = career_matches[0][0] if career_matches else "Software Developer"
    
    c.drawString(50, height - 310, f"Potential Career Direction: {top_career}")
    c.drawString(50, height - 325, f"Current Skills: {', '.join(student_skills) if student_skills else 'None'}")
    
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 50, "Generated by SmartCampus AI")
    c.drawString(50, 35, "Recommendations are AI-assisted guidance based on available student data and")
    c.drawString(50, 20, "should not be considered a guarantee of employment.")
    
    c.save()
    buffer.seek(0)
    return buffer

def render_pdf_report():
    st.markdown("## 📄 PDF Reports")
    
    
    if st.session_state.get("role") in ["admin", "teacher"]:
        from data import load_students_df
        df = load_students_df()
        active_sid = st.selectbox("Select Student", options=df["student_id"].tolist())
    else:
        active_sid = st.session_state.get("selected_student_id")

    if not active_sid:
        st.error("No student selected.")
        return
        
    st.markdown("Generate a comprehensive PDF report containing Academic Summary, Project Analysis, and Career Guidance.")
    
    pdf_buffer = generate_student_pdf(active_sid)
    
    st.download_button(
        label="Download PDF Report",
        data=pdf_buffer,
        file_name=f"{active_sid}_Report.pdf",
        mime="application/pdf"
    )
    
    st.info("Currently SmartCampus AI uses local/demo academic data. In a future implementation, the system can be integrated with the college ERP through secure APIs so that attendance, internal marks, external marks and other academic records can be fetched automatically.")
