[server]
port = 3000
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0077b6"
backgroundColor = "#f8faff"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"
