[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0077b6"
backgroundColor = "#f8faff"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"
